parameters:
    database_driver: pdo_mysql
    database_host: db.symfony
    database_port: '3306'
    database_name: symfony
    database_user: symfony
    database_password: zaq12wsx
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 02289cfc71fdade2cfd2805088ab4145e4ffc367
    database_path: null

